services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_DB}
      POSTGRES_USER: ${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY_ID: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_SECRET_ACCESS_KEY}
      MINIO_BUCKET_NAME: ${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_BUCKET_NAME}
    env_file:
      - .env
    networks:
      - app-network
    entrypoint: >
      /usr/bin/env sh -c '
      sleep 10 &&
      mc alias set myminio http://minio:9000 "$${MINIO_ROOT_USER}" "$${MINIO_ROOT_PASSWORD}" &&
      mc mb "myminio/$${MINIO_BUCKET_NAME}" &&
      mc admin accesskey create myminio/ --access-key "$${MINIO_ACCESS_KEY_ID}" --secret-key "$${MINIO_SECRET_ACCESS_KEY}"
      '
  
  backend:
    image: blocklune/csapp-lab-management-system-api
    environment:
      - CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_URL=jdbc:postgresql://postgres:5432/${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_DB}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_USERNAME=${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_USER}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_PASSWORD=${CSAPP_LAB_MANAGEMENT_SYSTEM_POSTGRES_PASSWORD}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_S3_ENDPOINT=http://minio:9000
      - CSAPP_LAB_MANAGEMENT_SYSTEM_S3_BUCKET_NAME=${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_BUCKET_NAME}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_S3_REGION=auto
      - CSAPP_LAB_MANAGEMENT_SYSTEM_S3_ACCESS_KEY_ID=${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_ACCESS_KEY_ID}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_S3_SECRET_ACCESS_KEY=${CSAPP_LAB_MANAGEMENT_SYSTEM_MINIO_SECRET_ACCESS_KEY}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_INIT_TEACHER_USERNAME=${CSAPP_LAB_MANAGEMENT_SYSTEM_INIT_TEACHER_USERNAME}
      - CSAPP_LAB_MANAGEMENT_SYSTEM_INIT_TEACHER_PASSWORD=${CSAPP_LAB_MANAGEMENT_SYSTEM_INIT_TEACHER_PASSWORD}
    env_file:
      - .env
    depends_on:
      - postgres
      - minio-init
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data:

networks:
  app-network:
    driver: bridge
